name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      version: "8.2"

  codeScan:
    name: "Code Scan"
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
  dockerbuild:
    name: "Docker Build and Push"
    needs: [test]
    uses: ./.github/workflows/docker-build.yaml
    secrets: 
      dockerpassword: ${{ secrets.PASSWORD }}

  trivyscan:
    name: "Trivy Scanning Image"
    needs: [dockerbuild]
    uses: ./.github/workflows/trivy-scan.yaml

           