name: Dockerize Laravel App

on: 
  workflow_call:
    secrets:
      dockerpassword:
        required: true
      

jobs:
  build:
    name: Dockerize Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.dockerpassword }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/verdent:${{ github.sha }}